import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Layout from '../components/layout/layout'
import { Provider } from 'next-auth/client'
import { useEffect } from 'react'
import { MessageProvider } from '../context/message-context'

const MyApp = ({ Component, pageProps }: AppProps) => {
  useEffect(() => {
    const jssStyles = document.querySelector('#jss-server-side')
    jssStyles?.parentElement?.removeChild(jssStyles)
  }, [])
  return (
    <Provider session={pageProps.session}>
      <MessageProvider>
        <Layout>
          <Head>
            <title>Next Typescript App</title>
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"
            />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </Layout>
      </MessageProvider>
    </Provider>
  )
}
export default MyApp
